### ISSUE TITLE
Cant access the content type for some reason

### ISSUE THREAD

**Issue by ckissi** [u12206050/gridsome-source-mysql#2]
I have this config

```
module.exports = {
  plugins: [
    {
      use: "gridsome-source-mysql",
      options: {
        connection: {
          host: "localhost", // required
          port: 3306,
          user: "root", // required
          password: "", // required
          database: "mydb", // required
          connectionLimit: 10
        },
        debug: true, // Default false on production
        ignoreImages: false, // Do not download any images
        imageDirectory: "sql_images",
        regex: /()_\d(.(jpg|png|svg|jpeg))/i, // Default false
        queries: [
          {
            name: "Theme",
            path: "slug",
            route: "/themes/:path",
            sql: `SELECT id, name, slug, author FROM themes WHERE slug=?`,
            args: [1]
          },
          {
            name: "Plugin",
            path: "slug",
            route: "/plugins/:path",
            sql: `SELECT id, name, slug, version,tested, rating FROM plugins WHERE slug=?`,
            args: [1]
          }
        ]
      }
    }
  ]
};
```

the query in the templates/Theme.vue looks like this:

```
<page-query>
query {
  themes: allTheme {
    edges {
      node {
        name
        slug        
      }
    }
  }
}
</page-query>
```

For some reason, I'm getting this error message:

```
Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "name" on type "Theme".

GraphQL request:13:9
12 |       node {
13 |         name
   |         ^
14 |         slug     

```

the field name is in the table as well as slug and other fields.

**Comment by u12206050** [comment]
Have you tried to view in the graphql explorer what types and fields are available?

**Comment by ckissi** [comment]
![image](https://user-images.githubusercontent.com/5107590/77959511-f956bb00-72d6-11ea-98da-4d90e34ca943.png)

 They are not there. But they exist in the DB.

![image](https://user-images.githubusercontent.com/5107590/77959673-45096480-72d7-11ea-82ce-62572a7c621c.png)

**Comment by u12206050** [comment]
What gridsome version are you using?

**Comment by ckissi** [comment]
@gridsome/cli v0.2.3
gridsome v0.7.13

**Comment by ckissi** [comment]
here is the SQL table: 

```CREATE TABLE `themes` (
  `id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `slug` varchar(100) NOT NULL,
  `g_order` int(11) DEFAULT NULL COMMENT 'Global order',
  `score_h` tinyint(1) DEFAULT 0,
  `score_p` tinyint(1) DEFAULT 0,
  `score_hm` tinyint(4) DEFAULT 0,
  `score_pm` tinyint(4) DEFAULT 0,
  `author` varchar(50) DEFAULT NULL,
  `version` varchar(10) DEFAULT NULL,
  `preview_url` varchar(100) DEFAULT NULL,
  `screenshot_url` varchar(100) DEFAULT NULL,
  `rating` tinyint(4) DEFAULT 0,
  `num_ratings` int(11) DEFAULT 0,
  `downloaded` int(11) DEFAULT 0,
  `last_updated` date DEFAULT NULL,
  `homepage` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `download_link` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `template` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_score_h` (`score_h`),
  KEY `idx_score_p` (`score_p`),
  KEY `idx_score_hm` (`score_hm`),
  KEY `idx_score_pm` (`score_pm`),
  KEY `idx_slug` (`slug`),
  FULLTEXT KEY `tags` (`tags`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;```

**Comment by ckissi** [comment]
As soon as I change the table name from 'plugins' to 'themes' it stops working:

this works:
```
{
        name: "Theme",
        path: "slug",
        route: "/themes/:path",
        sql: "SELECT id, `name`, slug FROM `plugins` WHERE slug=?",
        args: [1]
 }
```

This doesn't
```
{
       name: "Theme",
       path: "slug",
       route: "/themes/:path",
       sql: "SELECT id, `name`, slug FROM `themes` WHERE slug=?",
       args: [1]
 }
```

**Comment by u12206050** [comment]
Could it be an SQL permissions issue? btw, you don't need to specify `WHERE slug=?` 

What does the `___explore` give you if you start gridsome with this query:
`SELECT * FROM themes`

**Comment by ckissi** [comment]
Thanks. Started to work when I used without slug = ? :) 
 
```
queries: [
          {
            name: "Plugin",
            path: "slug",
            route: "/plugins/:path",
            sql: "SELECT * FROM plugins",
            args: [1]
          },
          {
            name: "Theme",
            path: "slug",
            route: "/themes/:path",
            sql: "SELECT * FROM `themes`",
            args: [1]
          }
        ]

```
Still one weird thing...
The ids seem to be like autogenerated:

```
{
  "data": {
    "allPlugin": {
      "edges": [
        {
          "node": {
            "id": "acdca4baaeac5e4550a7a000e17324ba",
            "name": "StageShow",
            "slug": "stageshow",
            "version": "4.5.6"
          }
        },
```

I use autoincrement ID in the table starting from 1. Is it possible to get the ids from the table instead of autogenerated?

**Comment by u12206050** [comment]
It is gridsome that adds the id field, it is used to map relationships etc. You can add this to your query if you still want the original id
`SELECT id as '_id', * FROM themes`

**Comment by ckissi** [comment]
thanks, I actually had to do this:

`SELECT id, id as _id, name, slug, version FROM `themes``

to select both the id and one with alias because I got an error that ID is missing.
