### ISSUE TITLE
image is null

### ISSUE THREAD

**Issue by tscole** [u12206050/gridsome-source-mysql#5]
I can't get images to work. My query is extremely long and complex so I don't want to post it here. The plugin recognises the image and correctly downloads them:

_267 images already exists with 0 images to download
Load sources - 4.55s
Create GraphQL schema - 0.45s
MySQL Connections Closed
Create pages and templates - 0.49s
Generate temporary code - 0.08s
Bootstrap finish - 6.47s_

I can see the files in the "sql_images" folder, but attempting to use them on the page results in a null value. Same thing querying in the GraphQL playground:

```
query {
  freesongs: allSong(filter: { freeSong: { eq: 1 }}) {
  edges{
    node {
      mysqlId
      id
      title
      image
    }
  }
}
}
```

Gets the result:

```
{
  "data": {
    "freesongs": {
      "edges": [
        {
          "node": {
            "mysqlId": 551,
            "id": "f4da3abd919affcbcf9b1891ecb8a19b",
            "title": "The Heart Of Worship",
            "image": null
          }
        }
      ]
    }
  }
}
```

**Comment by tscole** [comment]
If I comment out:

`images: ['image']`

I get the URL for the remote image returned by my query

**Comment by u12206050** [comment]
What version of Gridsome are you using?
Also are you sure that there aren't any images present on all of the `freesongs`. Maybe some don't have an image?

**Comment by tscole** [comment]
@gridsome/cli v0.3.3
gridsome v0.7.19

I am absolutely sure that the data I am using to test should have an image. If I run the SQL query defined in gridsome.config directly on the DB I correctly get an image field with a URL in it.

**Comment by tscole** [comment]
Apologies, I have realised what the problem is. Although the plugin downloaded the images the files themselves contained no data. I hadn't actually tried opening the files - I just saw that they were in the folder and assumed they were OK. Sorry! I had tried to pull them via the AWS Cloud Front CDN URL but the files are protected which is what caused the issue. Not the plugin at all.
